/**
 * Procode Endpoints for Conversational Skills
 * This document describes the following APIs that will be implemented by a watsonx Assistant client, and consumed by the watsonx Assistant team in order to enable the objectives set forth by the Conversational Skills Mission.
 *
 * OpenAPI spec version: 1.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageContextGlobal } from './messageContextGlobal';
import { MessageContextSkills } from './messageContextSkills';

export interface MessageContext {
  global?: MessageContextGlobal;
  skills?: MessageContextSkills;
  /**
   * An object containing context data that is specific to particular integrations. For more information, see the [documentation](https://cloud.ibm.com/docs/assistant?topic=assistant-dialog-integrations). This will include `chat.private.jwt` containing Cade's SSO security token.
   */
  integrations?: any;
}
