/**
 * Procode Endpoints for Conversational Skills
 * This document describes the following APIs that will be implemented by a watsonx Assistant client, and consumed by the watsonx Assistant team in order to enable the objectives set forth by the Conversational Skills Mission.
 *
 * OpenAPI spec version: 1.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseMessageContextSkill } from './baseMessageContextSkill';
import { MessageContextSkillSystem } from './messageContextSkillSystem';

export interface MessageContextDialogSkill extends BaseMessageContextSkill {
  /**
   * An object containing any arbitrary variables that can be read and written by a particular skill.
   */
  userDefined?: { [key: string]: any };
  system?: MessageContextSkillSystem;
}
