/**
 * Procode Endpoints for Conversational Skills
 * This document describes the following APIs that will be implemented by a watsonx Assistant client, and consumed by the watsonx Assistant team in order to enable the objectives set forth by the Conversational Skills Mission.
 *
 * OpenAPI spec version: 1.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * A reference to a media file to be sent as an attachment with the message.
 */
export interface MessageInputAttachment {
  /**
   * The URL of the media file.
   */
  url: string;
  /**
   * The media content type (such as a MIME type) of the attachment.
   */
  media_type?: string;
}
