/**
 * Procode Endpoints for Conversational Skills
 * This document describes the following APIs that will be implemented by a watsonx Assistant client, and consumed by the watsonx Assistant team in order to enable the objectives set forth by the Conversational Skills Mission.
 *
 * OpenAPI spec version: 1.0.11
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseMessageContextSkill } from './baseMessageContextSkill';

export interface MessageContextActionSkill extends BaseMessageContextSkill {
  /**
   * An object containing action variables. Action variables can be accessed only by steps in the same action, and do not persist after the action ends.
   */
  action_variables?: { [key: string]: any };
  /**
   * An object containing skill variables. (In the watsonx Assistant user interface, skill variables are called _session variables_.) Skill variables can be accessed by any action and persist for the duration of the session.
   */
  skill_variables?: { [key: string]: any };
}
